const fs = require('fs');
const path = require('path');
const base = 'c:/Users/Rupesh kumar sah/OneDrive/Desktop/rupesh3/frontend/src';

function write(file, lines) {
  const fullPath = path.join(base, file);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, lines.join('\n'));
  console.log('Wrote', file);
}

// Register
write('pages/Register.tsx', [
"import { useState } from 'react';",
"import { Link, useNavigate } from 'react-router-dom';",
"import { motion } from 'framer-motion';",
"import { Zap, User, Mail, Lock, Eye, EyeOff, Loader2 } from 'lucide-react';",
"import toast from 'react-hot-toast';",
"import { useAuthStore } from '../stores/authStore';",
"import Input from '../components/ui/Input';",
"import Button from '../components/ui/Button';",
"",
"export default function Register() {",
"  const navigate = useNavigate();",
"  const { register } = useAuthStore();",
"  const [name, setName] = useState('');",
"  const [email, setEmail] = useState('');",
"  const [password, setPassword] = useState('');",
"  const [showPassword, setShowPassword] = useState(false);",
"  const [loading, setLoading] = useState(false);",
"",
"  const handleSubmit = async (e: React.FormEvent) => {",
"    e.preventDefault();",
"    if (!name || !email || !password) { toast.error('Please fill in all fields'); return; }",
"    if (password.length < 8) { toast.error('Password must be at least 8 characters'); return; }",
"    setLoading(true);",
"    try { await register(name, email, password); toast.success('Account created!'); navigate('/'); }",
"    catch (err: any) { toast.error(err.response?.data?.message || 'Registration failed'); }",
"    finally { setLoading(false); }",
"  };",
"",
"  return (",
"    <div className=\"flex min-h-screen bg-slate-50 dark:bg-slate-950\">",
"      <div className=\"hidden lg:flex lg:w-1/2 relative overflow-hidden\">",
"        <div className=\"absolute inset-0 bg-violet-600\" />",
"        <div className=\"absolute inset-0 opacity-20 mix-blend-overlay\" style={{backgroundImage:'url(https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1600&q=80)',backgroundSize:'cover',backgroundPosition:'center'}} />",
"        <div className=\"relative z-10 flex flex-col justify-center px-16 text-white\">",
"          <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:0.2}}>",
"            <div className=\"flex items-center gap-3 mb-8\">",
"              <div className=\"h-12 w-12 rounded-xl bg-white/20 backdrop-blur flex items-center justify-center\"><Zap className=\"h-7 w-7 text-white\"/></div>",
"              <span className=\"text-2xl font-bold\">AI CRM</span>",
"            </div>",
"            <h1 className=\"text-4xl font-bold mb-4 leading-tight\">Start closing deals smarter</h1>",
"            <p className=\"text-lg text-violet-100 max-w-md\">Join thousands of sales teams using AI to predict conversions and automate their workflow.</p>",
"          </motion.div>",
"        </div>",
"      </div>",
"      <div className=\"flex-1 flex items-center justify-center p-6\">",
"        <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className=\"w-full max-w-sm\">",
"          <div className=\"text-center mb-8\">",
"            <div className=\"lg:hidden flex items-center justify-center gap-2 mb-6\">",
"              <div className=\"h-10 w-10 rounded-lg bg-violet-600 flex items-center justify-center\"><Zap className=\"h-6 w-6 text-white\"/></div>",
"              <span className=\"text-xl font-bold text-slate-900 dark:text-white\">AI CRM</span>",
"            </div>",
"            <h2 className=\"text-2xl font-bold text-slate-900 dark:text-white\">Create account</h2>",
"            <p className=\"text-sm text-slate-500 dark:text-slate-400 mt-1\">Get started for free</p>",
"          </div>",
"          <form onSubmit={handleSubmit} className=\"space-y-4\">",
"            <Input label=\"Full Name\" icon={<User className=\"h-4 w-4\"/>} value={name} onChange={e=>setName(e.target.value)} required/>",
"            <Input label=\"Email\" type=\"email\" icon={<Mail className=\"h-4 w-4\"/>} value={email} onChange={e=>setEmail(e.target.value)} required/>",
"            <div className=\"relative\">",
"              <Input label=\"Password\" type={showPassword?'text':'password'} icon={<Lock className=\"h-4 w-4\"/>} value={password} onChange={e=>setPassword(e.target.value)} required/>",
"              <button type=\"button\" onClick={()=>setShowPassword(!showPassword)} className=\"absolute right-3 top-[34px] text-slate-400 hover:text-slate-600\">{showPassword?<EyeOff className=\"h-4 w-4\"/>:<Eye className=\"h-4 w-4\"/>}</button>",
"            </div>",
"            <Button type=\"submit\" className=\"w-full\" disabled={loading}>{loading?<Loader2 className=\"h-4 w-4 animate-spin\"/>:'Create Account'}</Button>",
"          </form>",
"          <p className=\"text-center text-sm text-slate-500 dark:text-slate-400 mt-6\">Already have an account? <Link to=\"/login\" className=\"text-violet-600 hover:text-violet-700 font-medium\">Sign in</Link></p>",
"        </motion.div>",
"      </div>",
"    </div>",
"  );",
"}",
""
]);

// Dashboard
write('pages/Dashboard.tsx', [
"import { useQuery } from '@tanstack/react-query';",
"import { motion } from 'framer-motion';",
"import { Users, TrendingUp, DollarSign, Target, ArrowUpRight, ArrowDownRight } from 'lucide-react';",
"import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';",
"import PageHeader from '../components/common/PageHeader';",
"import Card from '../components/ui/Card';",
"import { api } from '../services/api';",
"",
"const COLORS = ['#7c3aed','#10b981','#f59e0b','#ef4444','#3b82f6','#8b5cf6'];",
"const container = { hidden:{opacity:0}, show:{opacity:1,transition:{staggerChildren:0.08}} };",
"const item = { hidden:{opacity:0,y:20}, show:{opacity:1,y:0} };",
"",
"export default function Dashboard() {",
"  const { data: analytics } = useQuery({",
"    queryKey: ['analytics'],",
"    queryFn: async () => { const res = await api.get('/analytics/dashboard'); return res.data.data; }",
"  });",
"",
"  const kpiData = [",
"    { label:'Total Leads', value: analytics?.totalLeads ?? 0, change:'+12%', up:true, icon:Users, color:'bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-400' },",
"    { label:'Conversion Rate', value: (analytics?.conversionRate ?? 0)+'%', change:'+3.2%', up:true, icon:TrendingUp, color:'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400' },",
"    { label:'Revenue', value: '$'+(analytics?.totalRevenue ?? 0).toLocaleString(), change:'+8.5%', up:true, icon:DollarSign, color:'bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-400' },",
"    { label:'Win Rate', value: (analytics?.winRate ?? 0)+'%', change:'-1.2%', up:false, icon:Target, color:'bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-400' },",
"  ];",
"",
"  const pipelineData = analytics?.pipelineDistribution?.map((d:any)=>({name:d._id,count:d.count})) ?? [];",
"  const sourceData = analytics?.sourceBreakdown?.map((d:any)=>({name:d._id,value:d.count})) ?? [];",
"",
"  return (",
"    <motion.div variants={container} initial=\"hidden\" animate=\"show\">",
"      <PageHeader title=\"Dashboard\" subtitle=\"Overview of your sales performance\" />",
"      <div className=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8\">",
"        {kpiData.map((kpi,i)=>(",
"          <motion.div key={i} variants={item}>",
"            <Card className=\"p-5\">",
"              <div className=\"flex items-start justify-between\">",
"                <div>",
"                  <p className=\"text-sm text-slate-500 dark:text-slate-400\">{kpi.label}</p>",
"                  <p className=\"text-2xl font-bold text-slate-900 dark:text-white mt-1\">{kpi.value}</p>",
"                  <div className={'flex items-center gap-1 mt-2 text-xs font-medium '+(kpi.up?'text-emerald-600':'text-rose-600')}>",
"                    {kpi.up?<ArrowUpRight className=\"h-3 w-3\"/>:<ArrowDownRight className=\"h-3 w-3\"/>}{kpi.change}",
"                  </div>",
"                </div>",
"                <div className={'p-2.5 rounded-lg '+kpi.color}><kpi.icon className=\"h-5 w-5\"/></div>",
"              </div>",
"            </Card>",
"          </motion.div>",
"        ))}",
"      </div>",
"      <div className=\"grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8\">",
"        <motion.div variants={item} className=\"lg:col-span-2\">",
"          <Card className=\"p-5\">",
"            <h3 className=\"text-sm font-semibold text-slate-900 dark:text-white mb-4\">Pipeline Distribution</h3>",
"            <div className=\"h-64\">",
"              <ResponsiveContainer width=\"100%\" height=\"100%\">",
"                <BarChart data={pipelineData}><CartesianGrid strokeDasharray=\"3 3\" stroke=\"#e2e8f0\"/><XAxis dataKey=\"name\" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip contentStyle={{borderRadius:8,border:'none',boxShadow:'0 4px 6px -1px rgb(0 0 0 / 0.1)'}}/><Bar dataKey=\"count\" fill=\"#7c3aed\" radius={[6,6,0,0]}/></BarChart>",
"              </ResponsiveContainer>",
"            </div>",
"          </Card>",
"        </motion.div>",
"        <motion.div variants={item}>",
"          <Card className=\"p-5\">",
"            <h3 className=\"text-sm font-semibold text-slate-900 dark:text-white mb-4\">Lead Sources</h3>",
"            <div className=\"h-64\">",
"              <ResponsiveContainer width=\"100%\" height=\"100%\">",
"                <PieChart><Pie data={sourceData} cx=\"50%\" cy=\"50%\" innerRadius={60} outerRadius={90} paddingAngle={4} dataKey=\"value\">{sourceData.map((_:any,i:number)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart>",
"              </ResponsiveContainer>",
"            </div>",
"          </Card>",
"        </motion.div>",
"      </div>",
"    </motion.div>",
"  );",
"}",
""
]);

// Leads
write('pages/Leads.tsx', [
"import { useState } from 'react';",
"import { useQuery } from '@tanstack/react-query';",
"import { motion } from 'framer-motion';",
"import { Plus, Search, Filter, Loader2, Mail, Building2 } from 'lucide-react';",
"import toast from 'react-hot-toast';",
"import PageHeader from '../components/common/PageHeader';",
"import Card from '../components/ui/Card';",
"import Button from '../components/ui/Button';",
"import Input from '../components/ui/Input';",
"import Select from '../components/ui/Select';",
"import Modal from '../components/ui/Modal';",
"import StatusBadge from '../components/common/StatusBadge';",
"import ScoreBadge from '../components/common/ScoreBadge';",
"import EmptyState from '../components/common/EmptyState';",
"import { api } from '../services/api';",
"import { Lead, LeadStatus } from '../types';",
"",
"const statusOptions = [",
"  { value:'', label:'All Statuses' },",
"  { value:'new', label:'New' },",
"  { value:'contacted', label:'Contacted' },",
"  { value:'qualified', label:'Qualified' },",
"  { value:'proposal', label:'Proposal' },",
"  { value:'won', label:'Won' },",
"  { value:'lost', label:'Lost' },",
"];",
"",
"export default function Leads() {",
"  const [search, setSearch] = useState('');",
"  const [status, setStatus] = useState('');",
"  const [showAdd, setShowAdd] = useState(false);",
"  const [newLead, setNewLead] = useState({name:'',email:'',company:'',source:'website' as any,status:'new' as LeadStatus});",
"",
"  const { data: leadsData, isLoading, refetch } = useQuery({",
"    queryKey: ['leads', search, status],",
"    queryFn: async () => {",
"      const params: any = { page:1, limit:50 };",
"      if (search) params.search = search;",
"      if (status) params.status = status;",
"      const res = await api.get('/leads', { params });",
"      return res.data.data;",
"    }",
"  });",
"",
"  const leads: Lead[] = leadsData?.data ?? [];",
"",
"  const handleAddLead = async (e: React.FormEvent) => {",
"    e.preventDefault();",
"    try {",
"      await api.post('/leads', newLead);",
"      toast.success('Lead created successfully');",
"      setShowAdd(false);",
"      setNewLead({name:'',email:'',company:'',source:'website',status:'new'});",
"      refetch();",
"    } catch (err: any) {",
"      toast.error(err.response?.data?.message || 'Failed to create lead');",
"    }",
"  };",
"",
"  return (",
"    <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}>",
"      <PageHeader title=\"Leads\" subtitle=\"Manage and track your leads\">",
"        <Button onClick={()=>setShowAdd(true)} icon={<Plus className=\"h-4 w-4\"/>}>Add Lead</Button>",
"      </PageHeader>",
"      <Card className=\"mb-6 p-4\">",
"        <div className=\"flex flex-col sm:flex-row gap-4\">",
"          <div className=\"flex-1\"><Input icon={<Search className=\"h-4 w-4\"/>} placeholder=\"Search leads...\" value={search} onChange={e=>setSearch(e.target.value)}/></div>",
"          <Select icon={<Filter className=\"h-4 w-4\"/>} options={statusOptions} value={status} onChange={e=>setStatus(e.target.value)} className=\"w-full sm:w-48\"/>",
"        </div>",
"      </Card>",
"      {isLoading ? (",
"        <div className=\"flex items-center justify-center py-20\"><Loader2 className=\"h-8 w-8 animate-spin text-violet-600\"/></div>",
"      ) : leads.length === 0 ? (",
"        <EmptyState title=\"No leads found\" description=\"Get started by adding your first lead.\" action={<Button onClick={()=>setShowAdd(true)} icon={<Plus className=\"h-4 w-4\"/>}>Add Lead</Button>}/>",
"      ) : (",
"        <div className=\"space-y-3\">",
"          {leads.map((lead: Lead)=>(",
"            <Card key={lead._id} className=\"p-4 hover:shadow-md transition-shadow cursor-pointer\">",
"              <div className=\"flex flex-col sm:flex-row sm:items-center justify-between gap-4\">",
"                <div className=\"flex items-start gap-4\">",
"                  <div className=\"h-10 w-10 rounded-full bg-violet-100 dark:bg-violet-500/20 flex items-center justify-center shrink-0\">",
"                    <span className=\"text-sm font-bold text-violet-600 dark:text-violet-400\">{lead.name[0]?.toUpperCase()}</span>",
"                  </div>",
"                  <div>",
"                    <h3 className=\"text-sm font-semibold text-slate-900 dark:text-white\">{lead.name}</h3>",
"                    <div className=\"flex items-center gap-3 mt-1 text-xs text-slate-500 dark:text-slate-400\">",
"                      <span className=\"flex items-center gap-1\"><Mail className=\"h-3 w-3\"/> {lead.email}</span>",
"                      <span className=\"flex items-center gap-1\"><Building2 className=\"h-3 w-3\"/> {lead.company}</span>",
"                    </div>",
"                  </div>",
"                </div>",
"                <div className=\"flex items-center gap-3\">",
"                  <StatusBadge status={lead.status}/>",
"                  {lead.score !== undefined && <ScoreBadge lead={lead} size=\"sm\" showLabel={false}/>}",
"                </div>",
"              </div>",
"            </Card>",
"          ))}",
"        </div>",
"      )}",
"      <Modal isOpen={showAdd} onClose={()=>setShowAdd(false)} title=\"Add New Lead\" description=\"Create a new lead in your CRM\">",
"        <form onSubmit={handleAddLead} className=\"space-y-4\">",
"          <Input label=\"Name\" value={newLead.name} onChange={e=>setNewLead({...newLead,name:e.target.value})} required/>",
"          <Input label=\"Email\" type=\"email\" value={newLead.email} onChange={e=>setNewLead({...newLead,email:e.target.value})} required/>",
"          <Input label=\"Company\" value={newLead.company} onChange={e=>setNewLead({...newLead,company:e.target.value})} required/>",
"          <Select label=\"Source\" options={[{value:'website',label:'Website'},{value:'linkedin',label:'LinkedIn'},{value:'referral',label:'Referral'},{value:'ads',label:'Ads'},{value:'event',label:'Event'}]} value={newLead.source} onChange={e=>setNewLead({...newLead,source:e.target.value})}/>",
"          <Select label=\"Status\" options={statusOptions.filter(o=>o.value)} value={newLead.status} onChange={e=>setNewLead({...newLead,status:e.target.value as LeadStatus})}/>",
"          <div className=\"flex gap-3 pt-2\">",
"            <Button type=\"button\" variant=\"secondary\" onClick={()=>setShowAdd(false)} className=\"flex-1\">Cancel</Button>",
"            <Button type=\"submit\" className=\"flex-1\">Create Lead</Button>",
"          </div>",
"        </form>",
"      </Modal>",
"    </motion.div>",
"  );",
"}",
""
]);

// Pipeline
write('pages/Pipeline.tsx', [
"import { useState } from 'react';",
"import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';",
"import { motion } from 'framer-motion';",
"import { GripVertical } from 'lucide-react';",
"import toast from 'react-hot-toast';",
"import PageHeader from '../components/common/PageHeader';",
"import ScoreBadge from '../components/common/ScoreBadge';",
"import EmptyState from '../components/common/EmptyState';",
"import { api } from '../services/api';",
"import { Lead, LeadStatus } from '../types';",
"",
"const columns: LeadStatus[] = ['new','contacted','qualified','proposal','won'];",
"const columnLabels: Record<string,string> = { new:'New', contacted:'Contacted', qualified:'Qualified', proposal:'Proposal', won:'Won' };",
"",
"export default function Pipeline() {",
"  const queryClient = useQueryClient();",
"  const [dragging, setDragging] = useState<string|null>(null);",
"",
"  const { data: leadsData, isLoading } = useQuery({",
"    queryKey: ['leads'],",
"    queryFn: async () => { const res = await api.get('/leads?limit=200'); return res.data.data.data ?? []; }",
"  });",
"",
"  const updateStatus = useMutation({",
"    mutationFn: async ({id,status}:{id:string;status:string}) => { await api.patch('/leads/'+id, {status}); },",
"    onSuccess: () => { queryClient.invalidateQueries({queryKey:['leads']}); toast.success('Lead moved'); }",
"  });",
"",
"  const leads: Lead[] = leadsData ?? [];",
"",
"  const handleDragStart = (leadId: string) => setDragging(leadId);",
"  const handleDragOver = (e: React.DragEvent) => e.preventDefault();",
"  const handleDrop = (e: React.DragEvent, status: LeadStatus) => {",
"    e.preventDefault();",
"    const leadId = e.dataTransfer.getData('leadId');",
"    if (leadId && dragging) { updateStatus.mutate({id:leadId, status}); setDragging(null); }",
"  };",
"",
"  return (",
"    <motion.div initial={{opacity:0}} animate={{opacity:1}}>",
"      <PageHeader title=\"Pipeline\" subtitle=\"Drag leads between stages to update their status\"/>",
"      {isLoading ? (",
"        <div className=\"flex items-center justify-center py-20\"><div className=\"h-8 w-8 border-2 border-violet-600 border-t-transparent rounded-full animate-spin\"/></div>",
"      ) : leads.length === 0 ? (",
"        <EmptyState title=\"No leads yet\" description=\"Add leads to see your pipeline.\"/>",
"      ) : (",
"        <div className=\"flex gap-4 overflow-x-auto pb-4\">",
"          {columns.map((col)=>(",
"            <div key={col} className=\"w-72 shrink-0\">",
"              <div className=\"flex items-center justify-between mb-3 px-1\">",
"                <h3 className=\"text-sm font-semibold text-slate-700 dark:text-slate-300\">{columnLabels[col]}</h3>",
"                <span className=\"text-xs text-slate-400 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-full\">{leads.filter((l:Lead)=>l.status===col).length}</span>",
"              </div>",
"              <div onDragOver={handleDragOver} onDrop={(e)=>handleDrop(e,col)} className={'min-h-[200px] rounded-xl p-2 space-y-2 transition-colors '+(dragging?'bg-slate-100 dark:bg-slate-800/50':'bg-slate-50 dark:bg-slate-900/50')}>",
"                {leads.filter((l:Lead)=>l.status===col).map((lead:Lead)=>(",
"                  <div key={lead._id} draggable onDragStart={(e)=>{e.dataTransfer.setData('leadId',lead._id); handleDragStart(lead._id);}} onDragEnd={()=>setDragging(null)}",
"                    className={'bg-white dark:bg-slate-800 rounded-lg p-3 shadow-sm cursor-grab active:cursor-grabbing border border-slate-100 dark:border-slate-700 hover:shadow-md transition-shadow '+(dragging===lead._id?'opacity-50':'')}>",
"                    <div className=\"flex items-start justify-between\">",
"                      <div>",
"                        <p className=\"text-sm font-medium text-slate-900 dark:text-white\">{lead.name}</p>",
"                        <p className=\"text-xs text-slate-500 dark:text-slate-400\">{lead.company}</p>",
"                      </div>",
"                      <GripVertical className=\"h-4 w-4 text-slate-300 shrink-0\"/>",
"                    </div>",
"                    <div className=\"flex items-center justify-between mt-3\">",
"                      {lead.score !== undefined ? <ScoreBadge lead={lead} size=\"sm\" showLabel={false}/> : <span/>}",
"                      <span className=\"text-xs text-slate-400\">${lead.estimatedValue ?? 0}</span>",
"                    </div>",
"                  </div>",
"                ))}",
"              </div>",
"            </div>",
"          ))}",
"        </div>",
"      )}",
"    </motion.div>",
"  );",
"}",
""
]);

// Activities
write('pages/Activities.tsx', [
"import { useState } from 'react';",
"import { useQuery } from '@tanstack/react-query';",
"import { motion } from 'framer-motion';",
"import { Phone, Mail, Calendar, StickyNote, CheckCircle, Loader2 } from 'lucide-react';",
"import PageHeader from '../components/common/PageHeader';",
"import Card from '../components/ui/Card';",
"import EmptyState from '../components/common/EmptyState';",
"import { api } from '../services/api';",
"import { Activity, ActivityType } from '../types';",
"",
"const typeIcons: Record<ActivityType, any> = { call:Phone, email:Mail, meeting:Calendar, note:StickyNote, task:CheckCircle, status_change:CheckCircle };",
"const typeColors: Record<ActivityType, string> = { call:'text-blue-600 bg-blue-50', email:'text-violet-600 bg-violet-50', meeting:'text-amber-600 bg-amber-50', note:'text-slate-600 bg-slate-50', task:'text-emerald-600 bg-emerald-50', status_change:'text-orange-600 bg-orange-50' };",
"",
"export default function Activities() {",
"  const { data: activities, isLoading } = useQuery({",
"    queryKey: ['activities'],",
"    queryFn: async () => { const res = await api.get('/activities'); return res.data.data ?? []; }",
"  });",
"",
"  const formatDate = (d: string) => new Date(d).toLocaleDateString('en-US', { month:'short', day:'numeric', hour:'2-digit', minute:'2-digit' });",
"",
"  return (",
"    <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}>",
"      <PageHeader title=\"Activities\" subtitle=\"Track all interactions with your leads\"/>",
"      {isLoading ? (",
"        <div className=\"flex items-center justify-center py-20\"><Loader2 className=\"h-8 w-8 animate-spin text-violet-600\"/></div>",
"      ) : !activities || activities.length === 0 ? (",
"        <EmptyState title=\"No activities yet\" description=\"Activities will appear here when you log calls, emails, or meetings.\"/>",
"      ) : (",
"        <div className=\"space-y-3\">",
"          {activities.map((activity: Activity)=>(",
"            <Card key={activity._id} className=\"p-4\">",
"              <div className=\"flex items-start gap-4\">",
"                <div className={'h-10 w-10 rounded-lg flex items-center justify-center shrink-0 '+(typeColors[activity.type] || 'text-slate-600 bg-slate-50')}",
"                  style={{backgroundColor:'transparent'}}>",
"                  {(()=>{ const Icon = typeIcons[activity.type] || StickyNote; return <Icon className=\"h-5 w-5\"/>; })()}",
"                </div>",
"                <div className=\"flex-1 min-w-0\">",
"                  <div className=\"flex items-center justify-between\">",
"                    <h3 className=\"text-sm font-semibold text-slate-900 dark:text-white\">{activity.title}</h3>",
"                    <span className=\"text-xs text-slate-400\">{formatDate(activity.createdAt)}</span>",
"                  </div>",
"                  {activity.description && <p className=\"text-sm text-slate-500 dark:text-slate-400 mt-1\">{activity.description}</p>}",
"                  <div className=\"flex items-center gap-2 mt-2\">",
"                    <span className=\"text-xs px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 capitalize\">{activity.type.replace('_',' ')}</span>",
"                  </div>",
"                </div>",
"              </div>",
"            </Card>",
"          ))}",
"        </div>",
"      )}",
"    </motion.div>",
"  );",
"}",
""
]);

console.log('All pages written successfully');
